create table
  public.todos (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    things character varying null,
    constraint todos_pkey primary key (id)
  ) tablespace pg_default;